#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# http://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pidFile=$DIR/target/universal/stage/RUNNING_PID

cd $DIR

case ${1:-} in
  start)
    sbt 'start -Dhttp.port=8084 -Dplay.evolutions.db.default.autoApply=true'
    ;;
  stop)
    if [[ -e $pidFile ]]; then
      kill `cat $pidFile`
    else
      echo "No PID file: $pidFile"
    fi
    ;;
  *)
    echo "Usage: prod [start | stop]"
    ;;
esac
