#!/usr/bin/env bash

# To set up on the server:
#   ln -s ../../scripts/post-receive .git/hooks/post-receive

# Allow pushing to the server even if it's an ordinary (non-bare) checkout:
#   git config receive.denyCurrentBranch updateInstead

# http://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
source="${BASH_SOURCE[0]}"
while [ -h "$source" ]; do
  scriptsDir="$( cd -P "$( dirname "$source" )" && pwd )"
  source="$(readlink "$source")"
  [[ $source != /* ]] && source="$scriptsDir/$source"
done
scriptsDir="$( cd -P "$( dirname "$source" )" && pwd )"

while read oldrev newrev refname
do
    # refname is like "refs/heads/master"
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [[ $branch == "master" ]]; then
        $scriptsDir/deploy
    fi
done
